#ifndef WIPS_H
#define WIPS_H

#include <vips/vips8>

#include <unordered_map>
#include <string>

static std::unordered_map<int, std::string> vips_interpretation_fmt = {
  {VIPS_INTERPRETATION_ERROR, "VIPS_INTERPRETATION_ERROR"},
  {VIPS_INTERPRETATION_MULTIBAND, "VIPS_INTERPRETATION_MULTIBAND"},
  {VIPS_INTERPRETATION_B_W, "VIPS_INTERPRETATION_B_W"},
  {VIPS_INTERPRETATION_HISTOGRAM, "VIPS_INTERPRETATION_HISTOGRAM"},
  {VIPS_INTERPRETATION_XYZ, "VIPS_INTERPRETATION_XYZ"},
  {VIPS_INTERPRETATION_LAB, "VIPS_INTERPRETATION_LAB"},
  {VIPS_INTERPRETATION_CMYK, "VIPS_INTERPRETATION_CMYK"},
  {VIPS_INTERPRETATION_LABQ, "VIPS_INTERPRETATION_LABQ"},
  {VIPS_INTERPRETATION_RGB, "VIPS_INTERPRETATION_RGB"},
  {VIPS_INTERPRETATION_CMC, "VIPS_INTERPRETATION_CMC"},
  {VIPS_INTERPRETATION_LCH, "VIPS_INTERPRETATION_LCH"},
  {VIPS_INTERPRETATION_LABS, "VIPS_INTERPRETATION_LABS"},
  {VIPS_INTERPRETATION_sRGB, "VIPS_INTERPRETATION_sRGB"},
  {VIPS_INTERPRETATION_YXY, "VIPS_INTERPRETATION_YXY"},
  {VIPS_INTERPRETATION_FOURIER, "VIPS_INTERPRETATION_FOURIER"},
  {VIPS_INTERPRETATION_RGB16, "VIPS_INTERPRETATION_RGB16"},
  {VIPS_INTERPRETATION_GREY16, "VIPS_INTERPRETATION_GREY16"},
  {VIPS_INTERPRETATION_MATRIX, "VIPS_INTERPRETATION_MATRIX"},  
  {VIPS_INTERPRETATION_scRGB, "VIPS_INTERPRETATION_scRGB"},
  {VIPS_INTERPRETATION_HSV, "VIPS_INTERPRETATION_HSV"},
  {VIPS_INTERPRETATION_LAST, "VIPS_INTERPRETATION_LAST"}
};

static std::unordered_map<int, std::string> vips_band_fmt = {
  {VIPS_FORMAT_NOTSET, "VIPS_FORMAT_NOTSET"},
  {VIPS_FORMAT_UCHAR, "VIPS_FORMAT_UCHAR"},  
  {VIPS_FORMAT_CHAR, "VIPS_FORMAT_CHAR"},
  {VIPS_FORMAT_USHORT, "VIPS_FORMAT_USHORT"},  
  {VIPS_FORMAT_UINT, "VIPS_FORMAT_UINT"},
  {VIPS_FORMAT_INT, "VIPS_FORMAT_INT"},  
  {VIPS_FORMAT_FLOAT, "VIPS_FORMAT_FLOAT"},
  {VIPS_FORMAT_COMPLEX, "VIPS_FORMAT_COMPLEX"},  
  {VIPS_FORMAT_DOUBLE, "VIPS_FORMAT_DOUBLE"},
  {VIPS_FORMAT_DPCOMPLEX, "VIPS_FORMAT_DPCOMPLEX"},
  {VIPS_FORMAT_LAST, "VIPS_FORMAT_LAST"}
};

#endif
